version: '3.8'

services:
  database-service:
    build: 
      context: ./database-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      # MongoDB Configuration (External Service)
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-hackit_db}
      - MONGODB_MAX_POOL_SIZE=${MONGODB_MAX_POOL_SIZE:-10}
      - MONGODB_MIN_POOL_SIZE=${MONGODB_MIN_POOL_SIZE:-1}
      
      # Redis Configuration (External Service) 
      - REDIS_URL=${REDIS_URL:-redis://localhost:6379}
      
      # API Security
      - API_SECRET_KEY=${API_SECRET_KEY}
      - API_RATE_LIMIT_ENABLED=${API_RATE_LIMIT_ENABLED:-true}
      - API_RATE_LIMIT_REQUESTS=${API_RATE_LIMIT_REQUESTS:-100}
      
      # Service Configuration
      - SERVICE_HOST=${SERVICE_HOST:-0.0.0.0}
      - SERVICE_PORT=${SERVICE_PORT:-8001}
      - SERVICE_NAME=${SERVICE_NAME:-hackit-database-service}
      - SERVICE_VERSION=${SERVICE_VERSION:-1.1.0}
      
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FORMAT=${LOG_FORMAT:-JSON}
      
      # Security & CORS
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-https://*.hackit.tw}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*.hackit.tw}
      
      # Performance & Features
      - CACHE_ENABLED=${CACHE_ENABLED:-false}
      - FEATURES_AUDIT_LOGGING=${FEATURES_AUDIT_LOGGING:-true}
      - FEATURES_SCHEMA_VALIDATION=${FEATURES_SCHEMA_VALIDATION:-true} 